config/routes.rb
TestApp::Application.routes.draw do
  resources :posts
  
  resources :users do
    member do
      get :following, :followers
    end
  end

  root :to => 'StaticPages#home'

  match '/sign_up', to: 'users#new'
  match '/sign_in', to: 'authentification#sign_in'
  match '/sign_out', to: 'authentification#sign_out'  #, via: :delete



  match '/help',  to: 'static_pages#help'
  match '/about',  to: 'static_pages#about'
  match '/contact',  to: 'static_pages#contact'















end

app/controllers/authentification_controller.rb
class AuthentificationController < ApplicationController

  def sign_in
    if params[:user]
      @user = User.authenticate(params[:user][:login], params[:user][:password])
      if @user
        cookies.permanent[:remember_token] = @user.remember_token
        current_user = @user

        session[:user_id] = @user.id
        session[:username] = @user.login

        flash[:success] = 'Vous etes maintenant connecte'
        redirect_to @user #'/index'
      else
        flash.now[:error_explanation] = 'Echec de connexion, votre login et/ou mot de passe sont incorrects'

      end
    end
  end


  def sign_out
    current_user = nil
    cookies.delete(:remember_token)

    reset_session
    session[:user_id] = nil
    session[:username] = nil

    flash[:warning] = "Vous etes maintenant deconnecte"
    redirect_to root_path #'/'
  end

end

app/helpers/authentification_helper.rb
module AuthentificationHelper
  def sign_in_after_signup(user)
    cookies.permanent[:remember_token] = user.remember_token
    current_user = user
  end
  
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  #store the request location, for redirecting after
  def store_location
    session[:return_to] = request.fullpath
  end

end

app/views/authentification/sign_in.html.erb
<% provide(:title, "Sign_in") %>
<h1 class="titre">Authentification</h1>

<div class="contenu">

    <%= form_tag  :controller => 'authentification', :action => 'sign_in' do %>
        <table>

          <tr>
            <td><%= label_tag "Login: " %></td>
            <td><%= text_field :user,:login, :class=>"txt" %></td>
          </tr>
          <tr>
            <td><%= label_tag "Mot de passe: " %></td>
            <td><%= password_field :user, :password, :class=>"txt" %></td>
          </tr>
          <tr>
            <td><%= submit_tag "Se connecter", :class=>"btn btn-large btn-primary"%></td>
          </tr>
        </table>
    <% end %>

  <p>Vous n'avez pas de compte? <%= link_to "Créer votre compte", sign_up_path %></p>
</div>

app/views/authentification/sign_out.html.erb
<h1>Authentification#sign_out</h1>
<p>Find me in app/views/authentification/sign_out.html.erb</p>