config/routes.rb
TestApp::Application.routes.draw do
  resources :posts
  
  resources :users do
    member do
      get :following, :followers
    end
  end

  root :to => 'StaticPages#home'

  match '/sign_up', to: 'users#new'
  match '/sign_in', to: 'authentification#sign_in'
  match '/sign_out', to: 'authentification#sign_out'  #, via: :delete



  match '/help',  to: 'static_pages#help'
  match '/about',  to: 'static_pages#about'
  match '/contact',  to: 'static_pages#contact'















end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">Test app</a>
    by GS
  </small>
  <nav>
    <ul>
      <li><%= link_to "About  |",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<!-- # encoding: utf-8 -->

<div id="header">
  <header class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to "My Test app logo", '#', id: "logo" %>
        <nav>
          <ul class="nav pull-right">
            <li><%= link_to "Accueil",    root_url %></li>
            <li><%= link_to "Aide",    '/help' %></li>
            <li><%= link_to "Créer mon compte", '/sign_up' %></li>

            <% if current_username != nil %>
                <li><%= link_to "Voir mon profil", current_user %></li>
                <li><%= link_to "Liste messages", posts_path %></li>
                <li><%= link_to "Déconnexion", sign_out_path, method: "delete" %></li>
            <% else %>
                <li><%= link_to "Connexion", '/sign_in' %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>
  </header>
  <div align="right" style="margin-right: 30px;">
    <% if current_username != nil %>
        Vous êtes connecté en tant que: <%= current_username %>
    <% else %>
        Vous n'êtes pas connecté
    <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
	
  <% @user ||= current_user %>
  
  <%= render 'layouts/header' %>

  <% flash.each do |key, msg| %>
    <% if key.eql?("error_explanation")%>
        <% content_tag :div, msg, :class => "error" %>
    <% else %>
        <%= content_tag :div, msg, :class => "notice" %>
    <% end %>
  <% end %>

  <div>
    <%= yield %>
  </div>
  
  <%= render 'layouts/footer' %>
</body>
</html>